### ISSUE TITLE
Issues with reproducing number in Paper

### ISSUE THREAD

**Issue by RPFey** [ZikeYan/activeINR#1]
Hi Zike, Thank you for sharing the work !

We have problems with reproducing the numbers in the paper. With the gibson.json config file, we run your model and get following results:

![image](https://github.com/ZikeYan/activeINR/assets/49940670/e4d70f83-e154-46a0-b90c-222f52b5b963)

It seems that the model can get very good accuracy but the comp metric is very low.

**Comment by ZikeYan** [comment]
Hi, thank you for your interest. We noticed that DD-PPO does not act properly to the target view on some devices. We will fix the issue ASAP (after the ECCV deadline). Sorry for your inconvenience.

**Comment by ZikeYan** [comment]
> Hi Zike, Thank you for sharing the work !
> 
> We have problems with reproducing the numbers in the paper. With the gibson.json config file, we run your model and get following results:
> 
> ![image](https://private-user-images.githubusercontent.com/49940670/309856014-e4d70f83-e154-46a0-b90c-222f52b5b963.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk1ODAwODEsIm5iZiI6MTcwOTU3OTc4MSwicGF0aCI6Ii80OTk0MDY3MC8zMDk4NTYwMTQtZTRkNzBmODMtZTE1NC00NmEwLWI5MGMtMjIyZjUyYjViOTYzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA0VDE5MTYyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY3MTIzMTUwZTdmMDA1NGQ0MGZlNGY3NGE1OTI0ZGM5ZjU1NTZhOTU0OWQ2ZTQyMWI4OTIyY2U3ZGEwMGE5MzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.5Xdn-0LEipp6aBQ3V7WK4KECP7q5_qZVHy2OpV-4BbU)
> 
> It seems that the model can get very good accuracy but the comp metric is very low.

Hi, thank you for your interest. We noticed that DD-PPO does not act properly to the target view on some devices. We will fix the issue ASAP (after the ECCV deadline) and the issue will remain to be open. Sorry for your inconvenience.

**Comment by RPFey** [comment]
Hi Zike, thanks for your reply. Also, I have a question about the comp (%) metric. In your evaluation file, I find comp_ratio and icomp_ratio. The first computes the distance from each sampled on gt mesh to recon mesh. The second computes the distance from recon mesh to gt mesh. Which one do you use in the paper ?

**Comment by ZikeYan** [comment]
> Hi Zike, thanks for your reply. Also, I have a question about the comp (%) metric. In your evaluation file, I find comp_ratio and icomp_ratio. The first computes the distance from each sampled on gt mesh to recon mesh. The second computes the distance from recon mesh to gt mesh. Which one do you use in the paper ?

acc*100 is the Acc. (cm) metric in our paper; (1-iratio)*100 is the FPR (%) metric.

**Comment by RPFey** [comment]
Thank you for your reply. It is appreciated. 

We do get similar numbers for the acc. Another thing I want to confirm is that the comp (instead of acc) I get is around 30 cm, is that normal ?

**Comment by ZikeYan** [comment]
> Thank you for your reply. It is appreciated.
> 
> We do get similar numbers for the acc. Another thing I want to confirm is that the comp (instead of acc) I get is around 30 cm, is that normal ?

It is possible as we cut the mesh that is above the agent for better visualization. We here mainly examine the reconstruction accuracy and false-positive zero-crossing surfaces as we evaluate the exploration completeness using eval_action. You can choose a smaller "Pruned height" value to keep the complete mesh for evaluation.

**Comment by ZikeYan** [comment]
> Hi Zike, Thank you for sharing the work !
> 
> We have problems with reproducing the numbers in the paper. With the gibson.json config file, we run your model and get following results:
> 
> ![image](https://private-user-images.githubusercontent.com/49940670/309856014-e4d70f83-e154-46a0-b90c-222f52b5b963.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA2NTk1NDEsIm5iZiI6MTcxMDY1OTI0MSwicGF0aCI6Ii80OTk0MDY3MC8zMDk4NTYwMTQtZTRkNzBmODMtZTE1NC00NmEwLWI5MGMtMjIyZjUyYjViOTYzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE3VDA3MDcyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYwODY4ZDUzY2M2OGEzYWIxMTg4OThmN2ViNThkNGRlOWQ4MmEyYzQyM2Q5NmQ3YmMwMDlhYWI2MWQ3ZTM3ZDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.FkwYDhBXHJCpaV3gXoUfTlXwTzGR09FgDs15C3CmlZA)
> 
> It seems that the model can get very good accuracy but the comp metric is very low.

Update:
We tested the algorithm on different devices. Pytorch 1.12.1 + CUDA10.2(that is the same as ours)/CUDA11.3  should reproduce the results. However, the behavior of DDPPO differs given different pytorch/CUDA versions and leads to different exploration completeness.

We have recently implemented the algorithm (weight perturbation for uncertainty quantification to find target views) with traditional path planning methods and updated NeRF-SLAM backbones. The performance will be more stable and better.
