### ISSUE TITLE
A question about the surface-perturb evaluation procession

### ISSUE THREAD

**Issue by dyb678** [ZikeYan/activeINR#2]
Thanks for your great work! I have a question about your code.In the part where the mesh undergoes perturb_eval, is it selecting the reconstructed mesh for clustering?

**Comment by ZikeYan** [comment]
> Thanks for your great work! I have a question about your code.In the part where the mesh undergoes perturb_eval, is it selecting the reconstructed mesh for clustering?

Hi, we quantify the variance against perturbation for all mesh vertices. The variance is then utilized for sub-goal clustering.
