### ISSUE TITLE
Release the training code

### ISSUE THREAD

**Issue by shiyao-li** [ZikeYan/activeINR#4]
Hi, thanks for your work! I noticed that this repository currently does not include the training code for the model.  I am wondering if you consider releasing it in the future. If so, could you please provide an estimated timeline for this? Thanks.

**Comment by ZikeYan** [comment]
> Hi, thanks for your work! I noticed that this repository currently does not include the training code for the model. I am wondering if you consider releasing it in the future. If so, could you please provide an estimated timeline for this? Thanks.

Hi, we use the pre-trained model of DD-PPO for point-goal navigation. If you wish to train your own policy, please follow the instruction in this repo: https://github.com/facebookresearch/habitat-lab/tree/main/habitat-baselines/habitat_baselines/rl/ddppo
